name: lint

on:
  push:
    paths:
      - '**.py'
      - .github/workflows/lint.yml
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/lint.yml
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install poetry
        run: pip install poetry
      - uses: actions/checkout@v3
      - name: Install linting tools
        run: poetry install --with=lint
      - name: Run flake8
        run: poetry run ruff check

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install poetry
        run: pip install poetry
      - uses: actions/checkout@v3
      - name: Install linting tools
        run: poetry install --with=lint,test
      - name: Run pyright
        run: poetry run pyright
