name: Lint

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          setup-version: '3.10'
      - uses: actions/checkout@v3
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy .
