name: test

on:
  push:
    paths:
      - '**.py'
      - .github/workflows/test.yml
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/test.yml
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        run: pip install poetry
      - uses: actions/checkout@v3
      - name: Install linting tools
        run: poetry install --with=test
      - name: Run pytest
        run: poetry run pytest
